import = ["/home/jaf/dots/alacritty/themes/themes/ayu_dark.toml"]

[font]
size = 14.0

[font.bold]
family = "Fira Code Nerd Font"
style = "Bold"

[font.italic]
family = "Fira Code Nerd Font"
style = "Italic"

[font.normal]
family = "Fira Code Nerd Font"
style = "Regular"

[selection]
save_to_clipboard = true

[shell]
program = "/bin/zsh"

[window]
opacity = 0.925

[window.padding]
x = 4
y = 4
