#!/usr/bin/env bash

current_dir=$(pwd)

config_dir="$HOME/.config"

mkdir -p "$config_dir"

for folder in */; do
  if [ -d "$folder" ]; then
    # Create a symbolic link to the .config folder
    ln -s "$current_dir/$folder" "$config_dir/"
  fi
done

echo "Symbolic links creation completed."

